# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d1740888930973f23b4201a4806522edc644b4d64557f5ef52a4925c6952370ac125a5498a70ec380a3915d60cf15932c4b186769e20720ab7d70786b77663ce

test:
  secret_key_base: eaecd5f3bf94e6ad435d2879e71fae71d388382c47e4fe87cbbac7b4215ecab1bb76bc320a115a2b1a871bf71512e8cc3f6c2784c0c483b7c66f331c2509e7e3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
